### ISSUE TITLE
Version mismatch with the product in Adafruit shop

### ISSUE THREAD

**Issue by JokerQyou** [adafruit/Adafruit-PN532-RFID-NFC-Breakout#1]
By following the link in the README document I saw the version of the PN532 NFC breakout board in Adafruit shop is `v1.6`, yet the files in this repository is still `v1.4`. 
Is `v1.6` not open sourced? Otherwise this repository need an update.

**Comment by chuenniger** [comment]
Hi

Is an update planned to v1.6?

Regards
Hu3nn1

**Comment by chuenniger** [comment]
THNQ :) - f011fcc28ce79a793011a1d2f870ae0eb7937fa7

You can close the ticket now

**Comment by JokerQyou** [comment]
Great. Good to know it's still actively maintained.
